"""
TASO – Dynamic Tool Generator

Uses a local LLM (preferably deepseek-coder via Ollama) to generate
new Python tools on demand. Generated tools are sandboxed-tested before
registration. Each tool exposes a `run_tool(input_data: dict) -> dict` interface.
"""
from __future__ import annotations
import ast
import re
import textwrap
import uuid
import json
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional

from config.logging_config import get_logger
from config.settings import settings
from models.ollama_client import ollama_chat

log = get_logger("tool_generator")

_GENERATOR_SYSTEM = """You are an expert Python tool developer for an autonomous security research platform.

Generate a single Python tool as a self-contained function `run_tool(input_data: dict) -> dict`.

Requirements:
- The function MUST be named exactly `run_tool`
- input_data is a dict with the inputs described in the task
- Return a dict with at minimum: {"success": bool, "result": ..., "error": str|None}
- No external imports beyond stdlib + these allowed: requests, aiohttp, subprocess, json, re, os, pathlib, hashlib, base64, datetime
- Keep it under 80 lines
- Add a docstring explaining what the tool does
- Include basic error handling with try/except

Return ONLY the Python code. No explanation, no markdown fences.
"""

_DESCRIPTION_SYSTEM = """You are a tool documentation expert.
Given a Python tool function, generate a JSON object with:
{
  "name": "snake_case_tool_name",
  "description": "one sentence description",
  "input_schema": {"field_name": "type description", ...},
  "output_schema": {"field_name": "type description", ...},
  "tags": ["tag1", "tag2"]
}
Return ONLY the JSON object.
"""


@dataclass
class GeneratedTool:
    id: str
    name: str
    description: str
    code: str
    input_schema: Dict[str, str]
    output_schema: Dict[str, str]
    tags: List[str] = field(default_factory=list)
    test_passed: bool = False
    test_output: str = ""
    version: str = "1.0.0"


class DynamicToolGenerator:
    """Generates, validates, and registers Python tools via LLM."""

    async def generate(self, task_description: str, tool_name: Optional[str] = None) -> GeneratedTool:
        """
        Full pipeline: generate code → validate syntax → extract metadata → return tool.
        Does NOT register or test — call sandbox_test() separately.
        """
        log.info(f"DynamicToolGenerator: generating tool for '{task_description[:60]}'")

        # 1. Generate code
        code = await self._generate_code(task_description)
        if not code:
            log.error("Failed to generate tool code: LLM returned no output")
            raise RuntimeError("LLM failed to generate tool code")

        # 2. Validate Python syntax
        try:
            code = self._clean_code(code)
            ast.parse(code)  # raises SyntaxError if invalid
        except SyntaxError as e:
            log.error(f"Generated code has invalid syntax: {e}")
            raise ValueError("Generated code contains invalid Python syntax") from e

        # 3. Ensure run_tool exists
        if "def run_tool" not in code:
            log.error("Generated code does not contain run_tool() function")
            raise ValueError("Generated code does not contain run_tool() function")

        # 4. Extract metadata
        metadata = await self._extract_metadata(code)
        name = tool_name or metadata.get("name", f"tool_{uuid.uuid4().hex[:8]}")

        return GeneratedTool(
            id=f"dyn_{uuid.uuid4().hex[:12]}",
            name=name,
            description=metadata.get("description", task_description[:100]),
            code=code,
            input_schema=metadata.get("input_schema", {}),
            output_schema=metadata.get("output_schema", {}),
            tags=metadata.get("tags", ["dynamic"]),
        )

    async def _generate_code(self, task: str) -> Optional[str]:
        """Generate Python tool code using available LLM models."""
        for model in ["deepseek-coder", settings.OLLAMA_MODEL, settings.OLLAMA_UNCENSORED_MODEL]:
            try:
                code = await ollama_chat(
                    model=model,
                    prompt=f"Create a Python tool that: {task}",
                    system=_GENERATOR_SYSTEM,
                    timeout=120,
                )
                if code and "def run_tool" in code:
                    log.info(f"DynamicToolGenerator: code generated by '{model}'")
                    return code
            except Exception as exc:
                log.warning(f"DynamicToolGenerator: model '{model}' failed: {exc}")
        log.error("All models failed to generate code")
        return None

    async def _extract_metadata(self, code: str) -> Dict:
        """Extract metadata from the generated tool code."""
        try:
            response = None
            try:
                from models.model_router import router
                response = await router.query(
                    prompt=f"Tool code:\n{code}\n\nGenerate metadata JSON.",
                    system=_DESCRIPTION_SYSTEM,
                )
            except Exception as router_exc:
                log.warning(f"Model router failed, falling back to Ollama: {router_exc}")
                response = await ollama_chat(
                    model=settings.OLLAMA_MODEL,
                    prompt=f"Tool code:\n{code}\n\nGenerate metadata JSON.",
                    system=_DESCRIPTION_SYSTEM,
                )
            if response:
                match = re.search(r'\{.*\}', response, re.DOTALL)
                if match:
                    return json.loads(match.group())
        except json.JSONDecodeError as json_exc:
            log.error(f"Failed to decode metadata JSON: {json_exc}")
        except Exception as exc:
            log.error(f"Unexpected error during metadata extraction: {exc}")
        return {}

    def _clean_code(self, code: str) -> str:
        """Strip markdown fences and normalize indentation."""
        try:
            code = re.sub(r'^```python\n?', '', code, flags=re.MULTILINE)
            code = re.sub(r'^```\n?', '', code, flags=re.MULTILINE)
            return textwrap.dedent(code).strip()
        except Exception as exc:
            log.error(f"Error cleaning code: {exc}")
            raise ValueError("Failed to clean generated code") from exc


tool_generator = DynamicToolGenerator()
